modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/bioastroiner/Additional-Worms/issues" #optional
[[mods]]
    modId="addworms"
    version="${version}"
    displayName="Additional Worms"

    #updateJSONURL="www.google.com"
    displayURL="www.reddit.com/r/feedthememes"
    logoFile="logo.png"
    credits="Credits to Actually Additon 's authors'"
    authors="Bioastroiner"
    description='''
first it adds back worms
then it adds more worms
    '''
[[dependencies.addworms]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.addworms]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"

